site_name: Bootstrap v5
use_directory_urls: false

plugins:
    - search
#    - pdf-export:
#        combined: true

nav:
- Contenidos: 'README.md'
- Introducción:
    - Introducción: '01_introduccion.md'
    - Frameworks responsive: '02_introduccion-frameworks.md'
    - Funcionamiento del diseño adaptable: '03_introduccion-funcionamiento.md'
    - Probando el responsive: '04_introduccion-pruebas.md'
- Página básica: '05_pagina-basica.md'
- Sistema de rejilla:
    - Funcionamiento: '06_rejilla.md'
    - Columnas de ancho específico: '07_rejilla-columnas-de-ancho-especifico.md'
    - Columnas de ancho automático: '08_rejilla-columnas-de-ancho-automatico.md'
    - Forzar el cambio de fila: '09_rejilla-forzar-el-cambio-de-fila.md'
    - Anidamiento de columnas: '10_rejilla-anidamiento-de-columnas.md'
    - Márgenes o espaciado entre columnas: '11_rejilla-margenes-o-espaciado-entre-columnas.md'
    - Ordenación de columnas: '12_rejilla-ordenacion-de-columnas.md'
    - Alineación: '13_rejilla-alineacion.md'
- Utilidades Responsive: '14_utilidades-responsive.md'
- Media Queries: '15_media-queries.md'
- Componentes:
    - Componentes Responsive: '16_componentes-responsive.md'
    - Botones: '17_componentes-botones.md'
    - Desplegables: '18_componentes-desplegables.md'
    - Grupos de botones: '19_componentes-grupos-de-botones.md'
    - Formularios: '20_componentes-formularios.md'
    - Navegación: '21_componentes-navegacion.md'
    - Barra de navegación: '22_componentes-barra-de-navegacion.md'
    - Tablas: '23_componentes-tablas.md'
- Ejercicios:
    - Ejercicios 1: '24_ejercicios-1.md'
    - Ejercicios 2: '25_ejercicios-2.md'
    - Ejercicios 3: '26_ejercicios-3.md'
    - Ejercicios 4: '27_ejercicios-4.md'
- Bibliografía: '28_bibliografia.md'


theme:
    language: es
    name: 'material'
    palette:
        primary: 'Indigo'
        accent: 'Indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: 'assets/logo.png'

# Ponemos como idioma de búsqueda el inglés
# para conseguir que busque correctamente
# todas las palabras en castellano, sin eliminar
# los excesivos derivados que se definen en
# https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.es.js

extra:
    search:
        language: 'en'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


#     - pymdownx.superfences
#    - pymdownx.arithmatex
markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - meta
    - sane_lists
    - toc:
       permalink: true
       toc_depth: 3
